//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBSSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Column
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Column()
        {
            this.tb_UserByRoleJoinColumn = new HashSet<tb_UserByRoleJoinColumn>();
        }
    
        /// <summary>
    	/// 
    	/// </summary>
        public int ID { get; set; }
        /// <summary>
    	/// 管理菜单编码
    	/// </summary>
        public string ColumnCode { get; set; }
        /// <summary>
    	/// 管理菜单名
    	/// </summary>
        public string ColumnName { get; set; }
        /// <summary>
    	/// 地址Url
    	/// </summary>
        public string Url { get; set; }
        /// <summary>
    	/// logo名
    	/// </summary>
        public string LogoClassName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_UserByRoleJoinColumn> tb_UserByRoleJoinColumn { get; set; }
    }
}
