//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBSSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ForumMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ForumMain()
        {
            this.tb_ForumInfoStatus = new HashSet<tb_ForumInfoStatus>();
            this.tb_ForumSecond = new HashSet<tb_ForumSecond>();
        }
    
        /// <summary>
    	/// 帖子编号
    	/// </summary>
        public int ID { get; set; }
        /// <summary>
    	/// 帖子标题
    	/// </summary>
        public string Title { get; set; }
        /// <summary>
    	/// 区域编号
    	/// </summary>
        public int ForumAreaID { get; set; }
        /// <summary>
    	/// 分类编号
    	/// </summary>
        public int ForumClassifyID { get; set; }
        /// <summary>
    	/// 发帖人编号
    	/// </summary>
        public int CreateUserID { get; set; }
        /// <summary>
    	/// 发帖时间
    	/// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
    	/// 发帖内容
    	/// </summary>
        public string Content { get; set; }
        /// <summary>
    	/// 是否推荐
    	/// </summary>
        public bool IsRecommend { get; set; }
        /// <summary>
    	/// 是否删除
    	/// </summary>
        public bool Isdelete { get; set; }
        /// <summary>
    	/// 是否审查
    	/// </summary>
        public int IsExamine { get; set; }
        /// <summary>
    	/// 点赞数量
    	/// </summary>
        public Nullable<int> Zan { get; set; }
    
        public virtual tb_ForumArea tb_ForumArea { get; set; }
        public virtual tb_ForumClassify tb_ForumClassify { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ForumInfoStatus> tb_ForumInfoStatus { get; set; }
        public virtual tb_UsersByCustomer tb_UsersByCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ForumSecond> tb_ForumSecond { get; set; }
    }
}
