//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBSSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ForumInfoStatus
    {
        /// <summary>
    	/// 自动编号
    	/// </summary>
        public int ID { get; set; }
        /// <summary>
    	/// 帖子编号
    	/// </summary>
        public int ForumMainID { get; set; }
        /// <summary>
    	/// 回复数量
    	/// </summary>
        public int ReplyNumber { get; set; }
        /// <summary>
    	/// 查看数量
    	/// </summary>
        public int SeeNumber { get; set; }
        /// <summary>
    	/// 最后一次回复人编号
    	/// </summary>
        public Nullable<int> LastReplyUserID { get; set; }
        /// <summary>
    	/// 最后一次回复时间
    	/// </summary>
        public Nullable<System.DateTime> LastReplytime { get; set; }
    
        public virtual tb_ForumMain tb_ForumMain { get; set; }
        public virtual tb_UsersByCustomer tb_UsersByCustomer { get; set; }
    }
}
