//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBSSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ForumSecond
    {
        /// <summary>
    	/// 回帖编号
    	/// </summary>
        public int ID { get; set; }
        /// <summary>
    	/// 帖子编号
    	/// </summary>
        public int ForumMainID { get; set; }
        /// <summary>
    	/// 回帖内容
    	/// </summary>
        public string Content { get; set; }
        /// <summary>
    	/// 回帖人
    	/// </summary>
        public int CreateUserID { get; set; }
        /// <summary>
    	/// 回帖时间
    	/// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
    	/// 最大楼层
    	/// </summary>
        public int CurSequence { get; set; }
        /// <summary>
    	/// 回复楼层
    	/// </summary>
        public int ReplySequenceID { get; set; }
        /// <summary>
    	/// 是否删除
    	/// </summary>
        public bool IsDelete { get; set; }
    
        public virtual tb_ForumMain tb_ForumMain { get; set; }
        public virtual tb_UsersByCustomer tb_UsersByCustomer { get; set; }
    }
}
