//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBSSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_UsersBySystem
    {
        /// <summary>
    	/// 版主编号
    	/// </summary>
        public int ID { get; set; }
        /// <summary>
    	/// 角色编号
    	/// </summary>
        public int RoleID { get; set; }
        /// <summary>
    	/// 版主用户名
    	/// </summary>
        public string UserName { get; set; }
        /// <summary>
    	/// 版主昵称
    	/// </summary>
        public string NickName { get; set; }
        /// <summary>
    	/// 版主密码
    	/// </summary>
        public byte[] UserPassword { get; set; }
        /// <summary>
    	/// 版主邮箱
    	/// </summary>
        public string Email { get; set; }
    
        public virtual tb_UserByRole tb_UserByRole { get; set; }
    }
}
