//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBSSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_UserByRoleJoinColumn
    {
        /// <summary>
    	/// 自动编号
    	/// </summary>
        public int ID { get; set; }
        /// <summary>
    	/// 角色编号
    	/// </summary>
        public int RoleID { get; set; }
        /// <summary>
    	/// 权限编号
    	/// </summary>
        public int ColumnID { get; set; }
    
        public virtual tb_Column tb_Column { get; set; }
        public virtual tb_UserByRole tb_UserByRole { get; set; }
    }
}
