//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBSSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_BBSEntities : DbContext
    {
        public DB_BBSEntities()
            : base("name=DB_BBSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Column> tb_Column { get; set; }
        public virtual DbSet<tb_ForumArea> tb_ForumArea { get; set; }
        public virtual DbSet<tb_ForumClassify> tb_ForumClassify { get; set; }
        public virtual DbSet<tb_ForumInfoStatus> tb_ForumInfoStatus { get; set; }
        public virtual DbSet<tb_ForumMain> tb_ForumMain { get; set; }
        public virtual DbSet<tb_ForumReport> tb_ForumReport { get; set; }
        public virtual DbSet<tb_ForumSecond> tb_ForumSecond { get; set; }
        public virtual DbSet<tb_UserByRole> tb_UserByRole { get; set; }
        public virtual DbSet<tb_UserByRoleJoinColumn> tb_UserByRoleJoinColumn { get; set; }
        public virtual DbSet<tb_UsersByCustomer> tb_UsersByCustomer { get; set; }
        public virtual DbSet<tb_UsersBySystem> tb_UsersBySystem { get; set; }
        public virtual DbSet<tb_ZY_ForumReportType> tb_ZY_ForumReportType { get; set; }
        public virtual DbSet<tb_ZY_ReportType> tb_ZY_ReportType { get; set; }
        public virtual DbSet<tb_ZY_Sex> tb_ZY_Sex { get; set; }
    }
}
