//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBSSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ForumArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ForumArea()
        {
            this.tb_ForumClassify = new HashSet<tb_ForumClassify>();
            this.tb_ForumMain = new HashSet<tb_ForumMain>();
        }
    
        /// <summary>
    	/// 区域编号
    	/// </summary>
        public int ID { get; set; }
        /// <summary>
    	/// 区域名称
    	/// </summary>
        public string AreaName { get; set; }
        /// <summary>
    	/// 创建者编号
    	/// </summary>
        public int UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ForumClassify> tb_ForumClassify { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ForumMain> tb_ForumMain { get; set; }
    }
}
